<?php die( 'These aren\'t the droids you\'re looking for.' );

/**
 * Extract of translatable text strings from the lib/pro classes.
 */
_x( 'Creative Work Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Default Family Friendly', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Publisher (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Publisher (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Service Prov. (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Service Prov. (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Default Physical Venue', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Organizer (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Organizer (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Performer (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Performer (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Posting Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Default Hiring Organization', 'option label', 'wpsso-schema-json-ld' );
_x( 'Default Job Location', 'option label', 'wpsso-schema-json-ld' );
_x( 'Review Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Default Subject Webpage Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Name / Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Alternate Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Description', 'option label', 'wpsso-schema-json-ld' );
_x( 'Microdata Type URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Same-As URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Creative Work Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Is Part of URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Headline', 'option label', 'wpsso-schema-json-ld' );
_x( 'Full Text', 'option label', 'wpsso-schema-json-ld' );
_x( 'Keywords', 'option label', 'wpsso-schema-json-ld' );
_x( 'Language', 'option label', 'wpsso-schema-json-ld' );
_x( 'Family Friendly', 'option label', 'wpsso-schema-json-ld' );
_x( 'Copyright Year', 'option label', 'wpsso-schema-json-ld' );
_x( 'License URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Publisher (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Publisher (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Service Prov. (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Service Prov. (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Audiobook Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Duration', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'How-To Makes', 'option label', 'wpsso-schema-json-ld' );
_x( 'Preparation Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Total Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Supplies', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Tools', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Steps', 'option label', 'wpsso-schema-json-ld' );
_x( '%1$s Step Details %2$s or New Section Details', 'option label', 'wpsso-schema-json-ld' );
_x( 'Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Description', 'option label', 'wpsso-schema-json-ld' );
_x( 'Image ID', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Recipe Cuisine', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Course', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Makes', 'option label', 'wpsso-schema-json-ld' );
_x( 'Cooking Method', 'option label', 'wpsso-schema-json-ld' );
_x( 'Preparation Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Cooking Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Total Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Ingredients', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Instructions', 'option label', 'wpsso-schema-json-ld' );
_x( 'Nutrition Information per Serving', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Serving Size', 'option label', 'wpsso-schema-json-ld' );
_x( 'Calories', 'option label', 'wpsso-schema-json-ld' );
_x( 'calories', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Protein', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of protein', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Fiber', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of fiber', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Carbohydrates', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of carbohydrates', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Sugar', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of sugar', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Sodium', 'option label', 'wpsso-schema-json-ld' );
_x( 'milligrams of sodium', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Saturated Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of saturated fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Unsaturated Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of unsaturated fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Trans Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of trans fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Cholesterol', 'option label', 'wpsso-schema-json-ld' );
_x( 'milligrams of cholesterol', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Movie Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Cast Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Director Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Production Company', 'option label', 'wpsso-schema-json-ld' );
_x( 'Movie Runtime', 'option label', 'wpsso-schema-json-ld' );
_x( 'Review Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Review Rating', 'option label', 'wpsso-schema-json-ld' );
_x( 'from', 'option comment', 'wpsso-schema-json-ld' );
_x( 'to', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Rating Value Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject of the Review', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Subject Webpage Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject Webpage URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject Same-As URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject Description', 'option label', 'wpsso-schema-json-ld' );
_x( 'Subject Image ID', 'option label', 'wpsso-schema-json-ld' );
_x( 'or an Image URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Creative Work Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'C.W. Author Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'C.W. Author Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'C.W. Author URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'C.W. Published Date', 'option label', 'wpsso-schema-json-ld' );
_x( 'C.W. Created Date', 'option label', 'wpsso-schema-json-ld' );
_x( 'Book Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Book ISBN', 'option label', 'wpsso-schema-json-ld' );
_x( 'Movie Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Movie Cast Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Movie Director Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Product Brand', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Offers', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Offer Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Offer Price', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Offer Currency', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Offer Availability', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product SKU', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product MPN', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Operating System', 'option label', 'wpsso-schema-json-ld' );
_x( 'Application Category', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Offers', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Offer Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Offer Price', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Offer Currency', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software App Offer Availability', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Subject Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Short Summary of Claim', 'option label', 'wpsso-schema-json-ld' );
_x( 'First Appearance URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software Application Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Operating System', 'option label', 'wpsso-schema-json-ld' );
_x( 'Application Category', 'option label', 'wpsso-schema-json-ld' );
_x( 'QA Page Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'QA Heading', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Event Language', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Attendance', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Online URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Physical Venue', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organizer (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organizer (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Performer (Org)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Performer (Person)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Status', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Start', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event End', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Previous Start', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offers Start', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offers End', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offers', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Price', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Currency', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Availability', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Posting Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Job Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Hiring Organization', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Location', 'option label', 'wpsso-schema-json-ld' );
_x( 'Base Salary', 'option label', 'wpsso-schema-json-ld' );
_x( 'per', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Employment Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Posting Expires', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organization Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Select an Organization', 'option label', 'wpsso-schema-json-ld' );
_x( 'Person Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Select a Person', 'option label', 'wpsso-schema-json-ld' );
_x( 'Additional Product Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Product Length', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Width', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Height', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Depth', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product Fluid Volume', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product GTIN-14', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product GTIN-13 (EAN)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product GTIN-12 (UPC)', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product GTIN-8', 'option label', 'wpsso-schema-json-ld' );
_x( 'Product GTIN', 'option label', 'wpsso-schema-json-ld' );
// translators: Please ignore - translation uses a different text domain.
_x( 'Maximum Images', 'option label', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
_x( 'Image ID', 'option label', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'days', 'option comment', 'wpsso-schema-json-ld' );
_x( 'hours', 'option comment', 'wpsso-schema-json-ld' );
_x( 'mins', 'option comment', 'wpsso-schema-json-ld' );
_x( 'secs', 'option comment', 'wpsso-schema-json-ld' );
